### ISSUE TITLE
question

### ISSUE THREAD

**Issue by liuguoqing1999** [gaviotas/AMN#10]
Hello, the idea of your article is very inspiring to me, but when running the code, it may be due to the different environment and computer configuration, resulting in the final result is not very ideal, do you have any suggestions for this problem?

**Comment by gaviotas** [comment]
Sorry for the late reply.

As previously [noted](https://github.com/gaviotas/AMN/issues/2#issuecomment-1191225465), performance variance is inherent in the training process. Therefore, it is advisable to repeat the entire process 2-3 times to ensure robustness and reliability. It is also recommended to use a single GPU during training.

Let me know if you have any further questions.

Thanks.

**Comment by xixiaos** [comment]
Hello author, I am very interested in your code. Could you please provide me with the relevant code for Coco? Thank you very much!

**Comment by gaviotas** [comment]
You can find the relevant code for COCO in this url :)

https://github.com/gaviotas/AMN/tree/coco14

Let me know if you have any further questions.

Thanks.

**Comment by xixiaos** [comment]
Hello author, thank you for your reply. I would like to ask how many cards you used while training Coco







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gaviotas/AMN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月30日(星期天) 上午10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gaviotas/AMN] question (Issue #10)





 
You can find the relevant code for COCO in this url :)
 
https://github.com/gaviotas/AMN/tree/coco14
 
Let me know if you have any further questions.
 
Thanks.

**Comment by gaviotas** [comment]
During the training of the COCO dataset, we used 4 x V100 GPUs.
