### ISSUE TITLE
the label

### ISSUE THREAD

**Issue by woqiaow** [gaviotas/AMN#5]

**Comment by woqiaow** [comment]
hi，
thanks for your code.
I would like to ask where the code of the label conditioning is?
I hope you can tell me， thanks！

**Comment by gaviotas** [comment]
Hello, @woqiaow.

You can find the code of the label conditioning in [net/resnet50_amn.py](https://github.com/gaviotas/AMN/blob/75c1999c7c1b59b776c69dc7370f93d53237c39d/net/resnet50_amn.py#L53-L60).

Please check it and let me know if you have any further questions.

**Comment by woqiaow** [comment]
Thank you,
I have no other problems at present.
