### ISSUE TITLE
the segmentation

### ISSUE THREAD

**Issue by woqiaow** [gaviotas/AMN#6]
Hello, I trained the segmentation network according to the link to deeplabv2 you gave me, using The train_aug.txt (10582) pseudo mask trained the segmentation network, and then verified with val.txt (1449), the result was only 0.03. Among the 21 classes, only the background is recognized, and the results of other classes are 0. Do I need to use a pseudo mask when verifying?

**Comment by gaviotas** [comment]
Sorry for the late reply.

Please check the following two things.

1) The pseudo-masks were generated correctly (please check the mIoU of the pseudo-mask with train.txt)
2) Please check the pre-trained model for the segmentation network. (e.g., ImageNet pre-trained model or MS-COCO pre-trained model)

Thanks.

**Comment by woqiaow** [comment]
That's OK. Thank you very much!
