### ISSUE TITLE
the step of make_sem_seg_pass is very time-consuming?

### ISSUE THREAD

**Issue by chentao2016** [gaviotas/AMN#7]
When I ran the code, I noticed that the step of make_sem_seg_pass is very time-consuming, especially for COCO with 80K images. Is it normal?

Is there any way to accelerate the pseudo-label generation?

**Comment by gaviotas** [comment]
Sorry for the late reply.

Unfortunately, the step of make_sem_seg_pass is a time-consuming process.
If you want to accelerate the pseudo-label generation step of make_sem_seg_pass, you need to use multiple GPUs by modifying the uploaded script. (e.g., CUDA_VISIBLE_DEVICES=0 --> CUDA_VISIBLE_DEVICES=0,1,2,3)

Thanks.
