### ISSUE TITLE
Results on VOC12

### ISSUE THREAD

**Issue by KatameRonin** [gaviotas/AMN#8]
Hi, thanks for the very organized repository. I have been trying to replicate the results achieved on the training set, however, the max I achieved with a single run of the entire pipeline is an mIOU of 70.7. Could you suggest reasons as to why that might be happening? 

Thanks

**Comment by gaviotas** [comment]
Sorry for the late reply.

As mentioned [here](https://github.com/gaviotas/AMN/issues/2#issuecomment-1191225465), there is a performance variance that comes from the training process. Therefore, it is recommended to conduct the entire process 2-3 times. Also, it is recommended to use a single GPU in the training process except for the inference.

About the question on [this](https://github.com/gaviotas/AMN/issues/2#issuecomment-1284599432), "training of the IRN network twice" means that ln 33-44 of the training script was performed twice (not a single run of the process).

Let me know if you have any further questions.

Thanks.
