### ISSUE TITLE
label smoothing

### ISSUE THREAD

**Issue by luckyjjj29** [gaviotas/AMN#9]
hi，thanks for your code.I would like to ask where the code of label smoothing as a training technique to subside the
noise in initial seed is? I hope you can tell me， thanks！

**Comment by gaviotas** [comment]
Hello, @luckyjjj29

You can check this part where the one-hot label is converted to the label-smoothed label.

https://github.com/gaviotas/AMN/blob/75c1999c7c1b59b776c69dc7370f93d53237c39d/step/train_amn.py#L142-L146
